version: "3.6"

networks:
  onlyoffice-network:
    name: onlyoffice-network
  nextcloud-network:
    name: nextcloud-network

x-oo-shared: &oo-shared
  networks:
    - onlyoffice-network
  # After 10 restarts don't try it again, otherwise it could affect other services on the host machine by restarting infinitely
  restart: on-failure:10
  # Limit the logging files to 10 with 100mb each, otherwise there is no limit until the disk is full
  logging:
    driver: "json-file"
    options:
      max-size: "100mb"
      max-file: "10"

services:
  # Document Server for Nextcloud OnlyOffice Connector
  documentserver:
    image: onlyoffice/documentserver:6.1.1
    container_name: documentserver
    depends_on:
      - postgres
      - ds-redis
      - rabbitmq
    env_file:
      - ./env_files/documentserver.env
    labels:
      - traefik.docker.network=nextcloud-network
      - traefik.frontend.rule=Host:${DOCUMENT_SERVER_DOMAIN}
      - traefik.port=80
    networks:
      - nextcloud-network
      - onlyoffice-network
    <<: *oo-shared

  # Redis for session/lock storage for OnlyOffice Documentserver
  ds-redis:
    image: redis:6.0.10-alpine
    container_name: ds-redis
    # Don't make it reachable outside of docker for security reasons
    labels:
      - traefik.enable=false
    <<: *oo-shared

  # Message Broker used by OnlyOffice Document Server
  rabbitmq:
    image: rabbitmq:3.8.11-alpine
    container_name: rabbitmq
    # Don't make it reachable outside of docker for security reasons
    labels:
      - traefik.enable=false
    <<: *oo-shared
